### ISSUE TITLE
Hawkears package version issue

### ISSUE THREAD

**Issue by sanruizguz** [kitzeslab/bioacoustics-model-zoo#10]
It is not possible to load the Hawkears model from zoo due to compatibility issues with the package timm, the full error can be found  [here](https://github.com/kitzeslab/bioacoustics-model-zoo/files/15391291/Hawkears_issue.txt), and the complete list of package versions installed in the virtual environment I used can be found 
[here](https://github.com/kitzeslab/bioacoustics-model-zoo/files/15391315/Hawkears_package_list.txt).

**Comment by sammlapp** [comment]
weird, the error seems to be related to retrieving a constant from this module https://github.com/huggingface/pytorch-image-models/blob/v1.0.3/timm/data/constants.py which has not changed in recent timm versions. I cannot reproduce the error so far. 

In my environment, I can write
```
from timm.data import OPENAI_CLIP_MEAN
OPENAI_CLIP_MEAN
```
and get `(0.48145466, 0.4578275, 0.40821073)`. 

What happens if you try this? 

Do you perhaps have a local clone of the timm repo on some other branch than the main release? That could be taking precedence over the pip installed version of timm

**Comment by sanruizguz** [comment]
This is the [full error.](https://github.com/kitzeslab/bioacoustics-model-zoo/files/15393723/Hawkears_full_error.txt)
